export interface InvoiceTemplate {
  id: string;
  name: string;
  description: string;
  preview: string;
  config: {
    template_name: string;
    primary_color: string;
    secondary_color: string;
    accent_color: string;
    text_color: string;
    font_family: 'helvetica' | 'times' | 'courier';
    font_size_base: number;
    font_size_heading: number;
    header_background_color: string;
    header_text_color: string;
    logo_position: 'top-left' | 'top-center' | 'top-right';
    show_company_slogan: boolean;
    show_line_numbers: boolean;
    show_tax_breakdown: boolean;
    show_bank_details: boolean;
    margin_top: number;
    margin_bottom: number;
    margin_left: number;
    margin_right: number;
  };
}

export const invoiceTemplates: InvoiceTemplate[] = [
  {
    id: 'modern',
    name: 'Modern',
    description: 'Modern mit blauem Akzent',
    preview: '🎨',
    config: {
      template_name: 'modern',
      primary_color: '#0ea5e9',
      secondary_color: '#64748b',
      accent_color: '#0284c7',
      text_color: '#1e293b',
      font_family: 'helvetica',
      font_size_base: 10,
      font_size_heading: 20,
      header_background_color: '#ffffff',
      header_text_color: '#1e293b',
      logo_position: 'top-left',
      show_company_slogan: true,
      show_line_numbers: true,
      show_tax_breakdown: true,
      show_bank_details: true,
      margin_top: 20,
      margin_bottom: 20,
      margin_left: 20,
      margin_right: 20,
    },
  },
  {
    id: 'classic',
    name: 'Klassisch',
    description: 'Traditionell mit Serifen',
    preview: '📜',
    config: {
      template_name: 'classic',
      primary_color: '#1e3a8a',
      secondary_color: '#475569',
      accent_color: '#1e40af',
      text_color: '#0f172a',
      font_family: 'times',
      font_size_base: 11,
      font_size_heading: 22,
      header_background_color: '#f8fafc',
      header_text_color: '#0f172a',
      logo_position: 'top-center',
      show_company_slogan: true,
      show_line_numbers: false,
      show_tax_breakdown: true,
      show_bank_details: true,
      margin_top: 25,
      margin_bottom: 25,
      margin_left: 25,
      margin_right: 25,
    },
  },
  {
    id: 'minimal',
    name: 'Minimalistisch',
    description: 'Reduziert, Fokus auf Inhalt',
    preview: '⬜',
    config: {
      template_name: 'minimal',
      primary_color: '#000000',
      secondary_color: '#737373',
      accent_color: '#404040',
      text_color: '#171717',
      font_family: 'helvetica',
      font_size_base: 9,
      font_size_heading: 18,
      header_background_color: '#ffffff',
      header_text_color: '#171717',
      logo_position: 'top-left',
      show_company_slogan: false,
      show_line_numbers: false,
      show_tax_breakdown: true,
      show_bank_details: true,
      margin_top: 15,
      margin_bottom: 15,
      margin_left: 15,
      margin_right: 15,
    },
  },
  {
    id: 'corporate',
    name: 'Corporate',
    description: 'Professionell und seriös',
    preview: '🏢',
    config: {
      template_name: 'corporate',
      primary_color: '#1e40af',
      secondary_color: '#64748b',
      accent_color: '#3b82f6',
      text_color: '#1e293b',
      font_family: 'helvetica',
      font_size_base: 10,
      font_size_heading: 20,
      header_background_color: '#f1f5f9',
      header_text_color: '#1e293b',
      logo_position: 'top-right',
      show_company_slogan: true,
      show_line_numbers: true,
      show_tax_breakdown: true,
      show_bank_details: true,
      margin_top: 20,
      margin_bottom: 20,
      margin_left: 20,
      margin_right: 20,
    },
  },
  {
    id: 'elegant',
    name: 'Elegant',
    description: 'Gehoben mit Gold-Akzent',
    preview: '✨',
    config: {
      template_name: 'elegant',
      primary_color: '#92400e',
      secondary_color: '#78716c',
      accent_color: '#b45309',
      text_color: '#292524',
      font_family: 'times',
      font_size_base: 10,
      font_size_heading: 22,
      header_background_color: '#fef3c7',
      header_text_color: '#78350f',
      logo_position: 'top-center',
      show_company_slogan: true,
      show_line_numbers: false,
      show_tax_breakdown: true,
      show_bank_details: true,
      margin_top: 25,
      margin_bottom: 25,
      margin_left: 25,
      margin_right: 25,
    },
  },
  {
    id: 'tech',
    name: 'Tech',
    description: 'Modern und technisch',
    preview: '💻',
    config: {
      template_name: 'tech',
      primary_color: '#6366f1',
      secondary_color: '#64748b',
      accent_color: '#4f46e5',
      text_color: '#1e293b',
      font_family: 'courier',
      font_size_base: 9,
      font_size_heading: 18,
      header_background_color: '#eef2ff',
      header_text_color: '#312e81',
      logo_position: 'top-left',
      show_company_slogan: true,
      show_line_numbers: true,
      show_tax_breakdown: true,
      show_bank_details: true,
      margin_top: 20,
      margin_bottom: 20,
      margin_left: 20,
      margin_right: 20,
    },
  },
  {
    id: 'green',
    name: 'Nachhaltig',
    description: 'Umweltbewusst mit Grün',
    preview: '🌱',
    config: {
      template_name: 'green',
      primary_color: '#16a34a',
      secondary_color: '#64748b',
      accent_color: '#15803d',
      text_color: '#1e293b',
      font_family: 'helvetica',
      font_size_base: 10,
      font_size_heading: 20,
      header_background_color: '#f0fdf4',
      header_text_color: '#14532d',
      logo_position: 'top-left',
      show_company_slogan: true,
      show_line_numbers: true,
      show_tax_breakdown: true,
      show_bank_details: true,
      margin_top: 20,
      margin_bottom: 20,
      margin_left: 20,
      margin_right: 20,
    },
  },
  {
    id: 'creative',
    name: 'Kreativ',
    description: 'Farbenfroh und kreativ',
    preview: '🎨',
    config: {
      template_name: 'creative',
      primary_color: '#dc2626',
      secondary_color: '#64748b',
      accent_color: '#ea580c',
      text_color: '#1e293b',
      font_family: 'helvetica',
      font_size_base: 10,
      font_size_heading: 22,
      header_background_color: '#fef2f2',
      header_text_color: '#7f1d1d',
      logo_position: 'top-center',
      show_company_slogan: true,
      show_line_numbers: false,
      show_tax_breakdown: true,
      show_bank_details: true,
      margin_top: 20,
      margin_bottom: 20,
      margin_left: 20,
      margin_right: 20,
    },
  },
  {
    id: 'professional',
    name: 'Professionell',
    description: 'Seriöses Business',
    preview: '📊',
    config: {
      template_name: 'professional',
      primary_color: '#334155',
      secondary_color: '#64748b',
      accent_color: '#475569',
      text_color: '#0f172a',
      font_family: 'helvetica',
      font_size_base: 10,
      font_size_heading: 20,
      header_background_color: '#f8fafc',
      header_text_color: '#0f172a',
      logo_position: 'top-right',
      show_company_slogan: true,
      show_line_numbers: true,
      show_tax_breakdown: true,
      show_bank_details: true,
      margin_top: 22,
      margin_bottom: 22,
      margin_left: 22,
      margin_right: 22,
    },
  },
  {
    id: 'handwerk',
    name: 'Handwerk',
    description: 'Robust für Handwerk',
    preview: '🔧',
    config: {
      template_name: 'handwerk',
      primary_color: '#ea580c',
      secondary_color: '#78716c',
      accent_color: '#c2410c',
      text_color: '#292524',
      font_family: 'helvetica',
      font_size_base: 11,
      font_size_heading: 20,
      header_background_color: '#fff7ed',
      header_text_color: '#7c2d12',
      logo_position: 'top-left',
      show_company_slogan: true,
      show_line_numbers: true,
      show_tax_breakdown: true,
      show_bank_details: true,
      margin_top: 20,
      margin_bottom: 20,
      margin_left: 20,
      margin_right: 20,
    },
  },
];

export function getTemplateById(id: string): InvoiceTemplate | undefined {
  return invoiceTemplates.find(t => t.id === id);
}

export function getDefaultTemplate(): InvoiceTemplate {
  return invoiceTemplates[0];
}
